name: HunterTag
main: com.imlucky.Loader
version: 1.0
commands:
  sethunter:
    description: Set a player as hunter.
    usage: /sethunter <player>
  setrunner:
    description: Set a player as runner.
    usage: /setrunner <player>
  startgame:
    description: Start the game.
    usage: /startgame
  resetall:
    description: Reset all role assignments.
    usage: /resetall
  resetpoints:
    description: Reset all player points.
    usage: /resetpoints
  challenge:
    description: Challenge a player.
    usage: /challenge <player>
  runkit:
    description: Give a player a runner kit.
    usage: /runkit <player>
  huntkit:
    description: Give a player a hunter kit.
    usage: /hunterkit <player>